services:
  mqtt-broker:
    # MQTT broker
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883" # MQTT (default)
      - "8083:8083" # MQTT over WebSockets
    volumes:
      - ./data/mosquitto-data:/mosquitto/data
      - ./data/mosquitto-logs:/mosquitto/logs
      - ./data/mosquitto-config:/mosquitto/config

  node-red:
    # Node-RED instance (http://localhost:1880)
    image: nodered/node-red:latest
    container_name: node-red
    depends_on:
      - mqtt-broker
    ports:
      - "1880:1880"
    volumes:
      - ./data/node-red-data:/data

  plc-sim:
    # Simulator for the CTF game (PLCs with OPC-UA)
    build: ./plc-sim
    ports:
      - "4840:4840" # OPC-UA PLC
    develop:
      watch:
        - action: sync+restart
          path: ./plc-sim
          target: /app
          initial_sync: true
